---
- name: Setup Icinga2 api if enabled
  shell: icinga2 api setup
  when: >
    "'api' in icinga2_enabled_features" and not
    icinga2_installed

- name: Configure Icinga2 api feature if present and not setup
  template:
    src: api.conf.j2
    dest: "{{ icinga2_install_path }}/features-available/api.conf"
    owner: "{{ icinga2_owner }}"
    group: "{{ icinga2_group }}"
  notify: restart icinga
  when: >
    "'api' in icinga2_enabled_features" and not
    icinga2_installed

- name: Configure API user and password
  template:
    src: api-users.conf.j2
    dest: "{{ icinga2_install_path }}/conf.d/api-users.conf"
    owner: "{{ icinga2_owner }}"
    group: "{{ icinga2_group }}"
  notify: restart icinga
  when: "'api' in icinga2_enabled_features"

- name: Generate TicketSalt for the first time
  shell: openssl rand -base64 30
  register: icinga2_ticket_salt
  when: >
    "'api' in icinga2_enabled_features" and not
    icinga2_installed

- name: Set Icinga2 TicketSalt once
  lineinfile:
    path: "{{ icinga2_install_path }}/constants.conf"
    regexp: "const TicketSalt =.*"
    line: 'const TicketSalt = "{{ icinga2_ticket_salt.stdout }}"'
  notify: restart icinga
  when: >
    "'api' in icinga2_enabled_features" and not
    icinga2_installed
...
