---
- name: Install Icinga2 web packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ icinga2_icingaweb_packages }}"

- name: Enable and start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: Enable and start httpd service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Configure Icinga2 web server (Apache)
  shell: icingacli setup config webserver apache
  when: >
    "icinga2_web_server == 'apache'" and not
    icinga2_installed
  notify: restart httpd
...
