---
- name: Set proper permissions on Icingaweb directory
  file:
    path: "{{ icinga2_web_install_path }}"
    state: directory
    recurse: yes
    owner: "{{ icinga2_web_owner }}"
    group: "{{ icinga2_web_group }}"
  when: not icinga2_installed

- name: Configure Graphite web
  template:
    src: web/graphite-web.conf.j2
    dest: /etc/httpd/conf.d/graphite-web.conf
  when: >
    "icinga2_web_server == 'apache'"
  notify: restart httpd

- name: Generate Icinga2 setup token
  shell: icingacli setup token create
  register: icinga2_setup_token
  when: not icinga2_installed

- name: Set proper permissions on setup token
  file:
    path: "{{ icinga2_web_install_path }}/setup.token"
    owner: "{{ icinga2_web_server }}"
    group: "{{ icinga2_web_group }}"
  when: not icinga2_installed

- debug:
    msg: "{{ icinga2_setup_token.stdout }}. Navigate to http://{{ ansible_default_ipv4.address }}/icingaweb2 in order to finish the setup."
  when: not icinga2_installed
...
