---
- name: Include distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- name: Install Icinga2
  include_tasks: install.yml

- name: Install MySQL server
  include_tasks: mysql-8.yml
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution_major_version == '8'

- name: Enable Icinga2 features
  include_tasks: features.yml
  when: icinga2_enabled_features is defined
...
