---
- name: Include distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if Icinga2 has been already installed
  stat:
    path: "{{ icinga2_install_path }}/installed"
  register: icinga2_install_chk
  ignore_errors: yes

- set_fact:
    icinga2_installed: True
  when: icinga2_install_chk.stat.exists

- set_fact:
    icinga2_installed: False
  when: not icinga2_install_chk.stat.exists

- name: Install MySQL server
  include_tasks: mysql-install.yml
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution_major_version == '8' and not
    icinga2_installed

- name: Configure MySQL
  include_tasks: mysql-configure.yml

- name: Install Icinga2
  include_tasks: icinga2-install.yml

- name: Enable Icinga2 features
  include_tasks: icinga-features.yml
  when: icinga2_enabled_features is defined

- name: Import initial Icinga2 MySQL schema
  include_tasks: import-mysql-schema.yml
  when: not icinga2_installed

- name: Install Icingaweb
  include_tasks: icinga-web.yml

- name: Install Icinga2 Graphite module
  include_tasks: icinga-graphite.yml
  when: "'graphite' in icinga2_enabled_features"

- name: Setup API
  include_tasks: icinga-api.yml

- name: Post-tasks for Icingaweb
  include_tasks: icinga-web-post.yml

- name: Mark Icinga2 as installed
  file:
    path: "{{ icinga2_install_path }}/installed"
    mode: 000
    state: touch
  when: not icinga2_installed

- name: Configure Icinga2 zone.conf
  include_tasks: icinga-zones.yml
  tags: configure_services

- name: Configure Icinga2 services
  include_tasks: icinga-serices.yml
  tags: configure_services

- name: Configure Icinga2 clients
  include_tasks: icinga-clients.yml
  when: >
    icinga2_client_group is defined and 
    (groups[icinga2_client_group]|length>0)
  tags: configure_clients
...
