---
- name: Include distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- name: Install Icinga2
  include_tasks: install.yml

- name: Install MySQL server
  include_tasks: mysql-install.yml
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution_major_version == '8'

- name: Configure MySQL
  include_tasks: mysql-configure.yml

- name: Enable Icinga2 features
  include_tasks: features.yml
  when: icinga2_enabled_features is defined

- name: Import initial Icinga2 MySQL schema
  include_tasks: import-mysql-schema.yml

- name: Install Icingaweb
  include_tasks: icinga-web.yml

- name: Install Icinga2 Graphite module
  include_tasks: icinga-graphite.yml
  when: "'graphite' in icinga2_enabled_features"

- name: Setup API
  include_tasks: api.yml
...
