---
- name: Install MySQL server
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ icinga2_mysql_packages }}"

- name: Enable and start MySQL server
  service:
    name: mysqld
    enabled: yes
    state: started

# This command will exit non-zero when the root password was set previously
- name: Check if root password is unset
  shell: >
    mysql -u root
    -p'{{ icinga2_mysql_root_password }}'
    -h localhost
    -S {{ icinga2_mysql_socket }}
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check

- name: Set MySQL root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ icinga2_mysql_root_password }}"
    host: localhost
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present
  when: root_pwd_check.rc != 0

- name: Set MySQL root password for 127.0.0.1, ::1, FQDN
  mysql_user:
    name: root
    password: "{{ icinga2_mysql_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - "{{ ansible_fqdn }}"
  when: root_pwd_check.rc == 0

- name: Set root MySQL password in /root/.my.cnf
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user="root"
      password="{{ icinga2_mysql_root_password }}"
...
