---
- name: Install MySQL server
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ icinga2_mysql_packages }}"

- name: Enable and start MySQL server
  service:
    name: mysqld
    enabled: yes
    state: started
...
