---
- name: Create user defined database for Icinga2
  mysql_db:
    name: "{{ icinga2_mysql_database }}"
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present
  register: db_created

- name: Create user defined database for Icinga2 Web
  mysql_db:
    name: "{{ icinga2_web_mysql_user }}"
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: absent
  no_log: true

- name: Create Icinga2 MySQL user for Icinga2
  mysql_user:
    name: "{{ icinga2_mysql_user }}"
    password: "{{ icinga2_mysql_user_password }}"
    host: "{{ icinga2_mysql_database_host|default('localhost') }}"
    priv: "{{ icinga2_mysql_database }}.*:ALL"
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present
  no_log: true

- name: Create Icinga2 MySQL user for Icinga2 Web
  mysql_user:
    name: "{{ icinga2_web_mysql_user }}"
    password: "{{ icinga2_web_mysql_user_password }}"
    host: "{{ icinga2_mysql_database_host|default('localhost') }}"
    priv: "{{ icinga2_web_mysql_database }}.*:ALL"
    login_user: root
    login_password: "{{ icinga2_mysql_root_password }}"
    login_unix_socket: "{{ icinga2_mysql_socket }}"
    state: present
  no_log: true
...
