---
- name: restart icinga
  service:
    name: icinga2
    state: restarted

- name: reload icinga
  service:
    name: icinga2
    state: reloaded

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart cabon-cache
  service:
    name: carbon-cache
    state: restarted
...
