---
- name: restart icinga2
  service:
    name: icinga2
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart cabon-cache
  service:
    name: carbon-cache
    state: restarted
...
